---
- name: Установка зависимостей
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes
  become: true

- name: Полностью размаскировать docker.service
  command: systemctl unmask docker.service
  become: true

- name: Создание директории для GPG-ключей Docker
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Скачивание GPG-ключа Docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Добавление репозитория
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    filename: docker
    state: present
  become: true

- name: Обновление кеша
  apt:
    update_cache: yes
  become: true

- name: Установка Docker пакетов
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  become: true


- name: Размаскировка и запуск Docker
  systemd:
    name: docker
    masked: no
    enabled: yes
    state: started
  become: true

- name: Проверка установки Docker
  shell: docker --version
  register: docker_output
  changed_when: false

- debug:
    var: docker_output.stdout


